// const testData = [
//   {
//     projectName: 'Project1',
//     list: [
//       {
//       name: 'Project1',
//       project: 'project1',
//       id: 1,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "project",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 1,
//     },
//     {
//       name: 'Task #1',
//       project: 'project1',
//       id: 2,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "task",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 2,
//     },
//     {
//       name: 'Task #2',
//       project: 'project1',
//       id: 3,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "task",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 3,
//     },
//     ],
//   },
//   {
//     projectName: 'Project #2',
//     list: [
//       {
//       name: 'Project #1',
//       project: 'project#2',
//       id: 1,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "project",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 1,
//     },
//     {
//       name: 'Task #1',
//       project: 'project#2',
//       id: 1,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "task",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 2,
//     },
//     {
//       name: 'Task #2',
//       project: 'project#2',
//       id: 1,
//       start: new Date(2020, 1, 6),
//       end: new Date(2020, 1, 10),
//       progress: 45,
//       type: "task",
//       styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//       // displayOrder: 3,
//     },
//     ],
//   },
//   {
//     projectName: 'Project #3',
//     list: [
//       {
//         name: 'Project #3',
//         project: 'project#3',
//         id: 1,
//         start: new Date(2020, 1, 6),
//         end: new Date(2020, 1, 10),
//         progress: 45,
//         type: "project",
//         styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//         // displayOrder: 1,
//       },
//       {
//         name: 'Task #1',
//         project: 'project#3',
//         id: 1,
//         start: new Date(2020, 1, 6),
//         end: new Date(2020, 1, 10),
//         progress: 45,
//         type: "task",
//         styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//         // displayOrder: 2,
//       },
//       {
//         name: 'Task #2',
//         project: 'project#3',
//         id: 1,
//         start: new Date(2020, 1, 6),
//         end: new Date(2020, 1, 10),
//         progress: 45,
//         type: "task",
//         styles: { progressColor: "#ffbb54", progressSelectedColor: "#ff9e0d" },
//         // displayOrder: 3,
//       },
//     ]
//   }
// ]
